w8.4: w8.4.o mergeInt.o
	gcc -Wall -o w8.4 w8.4.o mergeInt.o

w8.4.o: w8.4.c mergeInt.h
	gcc -Wall -o w8.4.o w8.4.c -g -c
	
mergeInt.o: mergeInt.c mergeInt.h
	gcc -Wall -o mergeInt.o mergeInt.c -g -c
